# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Beta Fortress Client (Linux)

on:
  push:
    branches: [ "master" ]
    paths:
      - '.github/**'
      - 'src/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - '.github/**'
      - 'src/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --runtime linux-x64
    #- name: Test
    # run: dotnet test --no-build --verbosity normal
    - name: Pack
      shell: bash
      run: tar cJfv build-rel-BFClient-net8.0-Linux.tar.xz bin/net8.0

    - name: Upload product
      uses: actions/upload-artifact@v4
      with:
          name: Beta Fortress Client - .NET 8.0 (Linux)
          path: build-rel-BFClient-net8.0-Linux.tar.xz
